pipeline {
    agent any
    stages {
        stage ("stage 1") {
            steps {
                echo "This is stage 1"
            }
        }
        stage ("stage 2") {
            steps {
                echo "This is stage 2"
            }
        }
        stage ("stage 3") {
            steps {
                echo "This is stage 3"
            }
        }
        stage ("stage 4") {
            steps {
                echo "This is stage 4"
            }
        }
        stage ("stage 5") {
            steps {
                echo "This is stage 5"
            }
        }
        stage ("stage 6") {
            steps {
                echo "This is the stage 6"
            }
        }
        stage ("new stage") {
            steps {
                echo "This is the new stage"
            }
        }
    }
}
